### ISSUE TITLE
Potential related work

### ISSUE THREAD

**Issue by Jiawei-Yang** [zhanghm1995/Forge_VFM4AD#1]
Hi there, thanks for your fabulous contribution regarding the rapid progress of this domain!

Our work EmerNeRF might also be interesting to your audience, which has already been accepted to ICLR2024 and is fully open-sourced. It is a purely self-supervised learning method that can model both static and dynamic components within the scene, as well as provide accurate scene flows and semantics understanding ability.

Here are some reference links:
web: https://emernerf.github.io/
code: https://github.com/NVlabs/EmerNeRF
paper: https://arxiv.org/abs/2311.02077

**Comment by zhanghm1995** [comment]
Thank you for your interest in our work, we have updated the EmerNeRF and it is indeed a very good work!
